# coding: utf-8

"""
    Paasta API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from paasta_tools.paastaapi.api_client import ApiClient
from paasta_tools.paastaapi.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class AutoscalerApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_autoscaler_count(self, service, instance, **kwargs):  # noqa: E501
        """Get status of service_name.instance_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_autoscaler_count(service, instance, async_req=True)
        >>> result = thread.get()

        :param service: Service name (required)
        :type service: str
        :param instance: Instance name (required)
        :type instance: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: AutoscalerCountMsg
        """
        kwargs['_return_http_data_only'] = True
        return self.get_autoscaler_count_with_http_info(service, instance, **kwargs)  # noqa: E501

    def get_autoscaler_count_with_http_info(self, service, instance, **kwargs):  # noqa: E501
        """Get status of service_name.instance_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_autoscaler_count_with_http_info(service, instance, async_req=True)
        >>> result = thread.get()

        :param service: Service name (required)
        :type service: str
        :param instance: Instance name (required)
        :type instance: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(AutoscalerCountMsg, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'service',
            'instance'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_autoscaler_count" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'service' is set
        if self.api_client.client_side_validation and ('service' not in local_var_params or  # noqa: E501
                                                        local_var_params['service'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `service` when calling `get_autoscaler_count`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if self.api_client.client_side_validation and ('instance' not in local_var_params or  # noqa: E501
                                                        local_var_params['instance'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `instance` when calling `get_autoscaler_count`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'service' in local_var_params:
            path_params['service'] = local_var_params['service']  # noqa: E501
        if 'instance' in local_var_params:
            path_params['instance'] = local_var_params['instance']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/services/{service}/{instance}/autoscaler', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AutoscalerCountMsg',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def update_autoscaler_count(self, service, instance, autoscaler_count_msg, **kwargs):  # noqa: E501
        """Get status of service_name.instance_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_autoscaler_count(service, instance, autoscaler_count_msg, async_req=True)
        >>> result = thread.get()

        :param service: Service name (required)
        :type service: str
        :param instance: Instance name (required)
        :type instance: str
        :param autoscaler_count_msg: (required)
        :type autoscaler_count_msg: AutoscalerCountMsg
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: AutoscalerCountMsg
        """
        kwargs['_return_http_data_only'] = True
        return self.update_autoscaler_count_with_http_info(service, instance, autoscaler_count_msg, **kwargs)  # noqa: E501

    def update_autoscaler_count_with_http_info(self, service, instance, autoscaler_count_msg, **kwargs):  # noqa: E501
        """Get status of service_name.instance_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_autoscaler_count_with_http_info(service, instance, autoscaler_count_msg, async_req=True)
        >>> result = thread.get()

        :param service: Service name (required)
        :type service: str
        :param instance: Instance name (required)
        :type instance: str
        :param autoscaler_count_msg: (required)
        :type autoscaler_count_msg: AutoscalerCountMsg
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(AutoscalerCountMsg, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'service',
            'instance',
            'autoscaler_count_msg'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_autoscaler_count" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'service' is set
        if self.api_client.client_side_validation and ('service' not in local_var_params or  # noqa: E501
                                                        local_var_params['service'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `service` when calling `update_autoscaler_count`")  # noqa: E501
        # verify the required parameter 'instance' is set
        if self.api_client.client_side_validation and ('instance' not in local_var_params or  # noqa: E501
                                                        local_var_params['instance'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `instance` when calling `update_autoscaler_count`")  # noqa: E501
        # verify the required parameter 'autoscaler_count_msg' is set
        if self.api_client.client_side_validation and ('autoscaler_count_msg' not in local_var_params or  # noqa: E501
                                                        local_var_params['autoscaler_count_msg'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `autoscaler_count_msg` when calling `update_autoscaler_count`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'service' in local_var_params:
            path_params['service'] = local_var_params['service']  # noqa: E501
        if 'instance' in local_var_params:
            path_params['instance'] = local_var_params['instance']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'autoscaler_count_msg' in local_var_params:
            body_params = local_var_params['autoscaler_count_msg']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/services/{service}/{instance}/autoscaler', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AutoscalerCountMsg',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))
