#!/usr/bin/python
# -*- coding: utf-8 -*-

from setuptools import setup, find_packages


setup(
    name           = 'paasta-tools',
    version        = '0.9.61',
    provides       = ["paasta_tools"],
    author         = 'Kyle Anderson',
    author_email   = 'kwa@yelp.com',
    description    = 'Tools for Yelps SOA infrastructure',
    packages       = find_packages(exclude=["tests", "scripts"]),
    setup_requires = ['setuptools'],
    include_package_data=True,
    install_requires = [
        'argcomplete >= 0.8.1',
        'argparse >= 1.2.1',
        'docker-py >= 0.5.3',
        'dulwich >= 0.9.8',
        'humanize >= 0.5.1',
        'isodate >= 0.5.0',
        'kazoo >= 2.0.0',
        'marathon >= 0.6.13',
        'mesos.cli >= 0.1.3',
        'ordereddict >= 1.1',
        'pysensu-yelp >= 0.1.5',
        'python-dateutil >= 2.4.0',
        'requests >= 2.6.0',
        'scribereader >= 0.1.8',
        'sensu-plugin >= 0.1.0',
        'service-configuration-lib >= 0.9.2',
        # scribereader requires this version
        'yelp_clog == 1.4.2',
    ],
    scripts = [
        'paasta_tools/setup_marathon_job.py',
        'paasta_tools/setup_chronos_jobs.py',
        'paasta_tools/am_i_mesos_leader.py',
        'paasta_tools/synapse_srv_namespaces_fact.py',
        'paasta_tools/cleanup_marathon_jobs.py',
        'paasta_tools/check_marathon_services_frontends.py',
        'paasta_tools/list_marathon_service_instances.py',
        'paasta_tools/monitoring/check_synapse_replication.py',
        'paasta_tools/monitoring/check_classic_service_replication.py',
        'paasta_tools/deploy_marathon_services',
        'paasta_tools/generate_all_deployments',
        'paasta_tools/generate_deployments_for_service.py',
        'paasta_tools/check_marathon_services_replication.py',
        'paasta_tools/check_mesos_resource_utilization.py',
        'paasta_tools/generate_services_yaml.py',
        'paasta_tools/generate_services_file.py',
        'paasta_tools/paasta_serviceinit.py',
        'paasta_tools/paasta_metastatus.py',
        'paasta_tools/paasta_cli/paasta_cli.py',
        'paasta_tools/paasta_cli/paasta_tabcomplete.sh',
    ],
    package_data = {'': ['paasta_cli/fsm/templates/*.tmpl']},
)
