# coding: utf-8

"""
    Paasta API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from paasta_tools.paastaapi.configuration import Configuration


class InstanceStatusKubernetesAutoscalingStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'desired_replicas': 'int',
        'last_scale_time': 'str',
        'max_instances': 'int',
        'metrics': 'list[HPAMetric]',
        'min_instances': 'int'
    }

    attribute_map = {
        'desired_replicas': 'desired_replicas',
        'last_scale_time': 'last_scale_time',
        'max_instances': 'max_instances',
        'metrics': 'metrics',
        'min_instances': 'min_instances'
    }

    def __init__(self, desired_replicas=None, last_scale_time=None, max_instances=None, metrics=None, min_instances=None, local_vars_configuration=None):  # noqa: E501
        """InstanceStatusKubernetesAutoscalingStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._desired_replicas = None
        self._last_scale_time = None
        self._max_instances = None
        self._metrics = None
        self._min_instances = None
        self.discriminator = None

        if desired_replicas is not None:
            self.desired_replicas = desired_replicas
        if last_scale_time is not None:
            self.last_scale_time = last_scale_time
        if max_instances is not None:
            self.max_instances = max_instances
        if metrics is not None:
            self.metrics = metrics
        if min_instances is not None:
            self.min_instances = min_instances

    @property
    def desired_replicas(self):
        """Gets the desired_replicas of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501

        desired number of _instances as calculated by HPA  # noqa: E501

        :return: The desired_replicas of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :rtype: int
        """
        return self._desired_replicas

    @desired_replicas.setter
    def desired_replicas(self, desired_replicas):
        """Sets the desired_replicas of this InstanceStatusKubernetesAutoscalingStatus.

        desired number of _instances as calculated by HPA  # noqa: E501

        :param desired_replicas: The desired_replicas of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :type desired_replicas: int
        """

        self._desired_replicas = desired_replicas

    @property
    def last_scale_time(self):
        """Gets the last_scale_time of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501

        timestamp of last autoscale  # noqa: E501

        :return: The last_scale_time of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :rtype: str
        """
        return self._last_scale_time

    @last_scale_time.setter
    def last_scale_time(self, last_scale_time):
        """Sets the last_scale_time of this InstanceStatusKubernetesAutoscalingStatus.

        timestamp of last autoscale  # noqa: E501

        :param last_scale_time: The last_scale_time of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :type last_scale_time: str
        """

        self._last_scale_time = last_scale_time

    @property
    def max_instances(self):
        """Gets the max_instances of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501

        min_instances as specified in yelpsoa_configs  # noqa: E501

        :return: The max_instances of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :rtype: int
        """
        return self._max_instances

    @max_instances.setter
    def max_instances(self, max_instances):
        """Sets the max_instances of this InstanceStatusKubernetesAutoscalingStatus.

        min_instances as specified in yelpsoa_configs  # noqa: E501

        :param max_instances: The max_instances of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :type max_instances: int
        """

        self._max_instances = max_instances

    @property
    def metrics(self):
        """Gets the metrics of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501

        Current metrics  # noqa: E501

        :return: The metrics of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :rtype: list[HPAMetric]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this InstanceStatusKubernetesAutoscalingStatus.

        Current metrics  # noqa: E501

        :param metrics: The metrics of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :type metrics: list[HPAMetric]
        """

        self._metrics = metrics

    @property
    def min_instances(self):
        """Gets the min_instances of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501

        min_instances as specified in yelpsoa_configs  # noqa: E501

        :return: The min_instances of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :rtype: int
        """
        return self._min_instances

    @min_instances.setter
    def min_instances(self, min_instances):
        """Sets the min_instances of this InstanceStatusKubernetesAutoscalingStatus.

        min_instances as specified in yelpsoa_configs  # noqa: E501

        :param min_instances: The min_instances of this InstanceStatusKubernetesAutoscalingStatus.  # noqa: E501
        :type min_instances: int
        """

        self._min_instances = min_instances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstanceStatusKubernetesAutoscalingStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InstanceStatusKubernetesAutoscalingStatus):
            return True

        return self.to_dict() != other.to_dict()
