# coding: utf-8

"""
    Paasta API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from paasta_tools.paastaapi.configuration import Configuration


class KubernetesContainer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'tail_lines': 'TaskTailLines'
    }

    attribute_map = {
        'name': 'name',
        'tail_lines': 'tail_lines'
    }

    def __init__(self, name=None, tail_lines=None, local_vars_configuration=None):  # noqa: E501
        """KubernetesContainer - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._tail_lines = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if tail_lines is not None:
            self.tail_lines = tail_lines

    @property
    def name(self):
        """Gets the name of this KubernetesContainer.  # noqa: E501

        Name of the container  # noqa: E501

        :return: The name of this KubernetesContainer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this KubernetesContainer.

        Name of the container  # noqa: E501

        :param name: The name of this KubernetesContainer.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def tail_lines(self):
        """Gets the tail_lines of this KubernetesContainer.  # noqa: E501


        :return: The tail_lines of this KubernetesContainer.  # noqa: E501
        :rtype: TaskTailLines
        """
        return self._tail_lines

    @tail_lines.setter
    def tail_lines(self, tail_lines):
        """Sets the tail_lines of this KubernetesContainer.


        :param tail_lines: The tail_lines of this KubernetesContainer.  # noqa: E501
        :type tail_lines: TaskTailLines
        """

        self._tail_lines = tail_lines

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubernetesContainer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubernetesContainer):
            return True

        return self.to_dict() != other.to_dict()
