# coding: utf-8

"""
    Paasta API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from paasta_tools.paastaapi.configuration import Configuration


class MarathonMesosStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error_message': 'str',
        'non_running_tasks': 'list[MarathonMesosNonrunningTask]',
        'running_task_count': 'int',
        'running_tasks': 'list[MarathonMesosRunningTask]'
    }

    attribute_map = {
        'error_message': 'error_message',
        'non_running_tasks': 'non_running_tasks',
        'running_task_count': 'running_task_count',
        'running_tasks': 'running_tasks'
    }

    def __init__(self, error_message=None, non_running_tasks=None, running_task_count=None, running_tasks=None, local_vars_configuration=None):  # noqa: E501
        """MarathonMesosStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._error_message = None
        self._non_running_tasks = None
        self._running_task_count = None
        self._running_tasks = None
        self.discriminator = None

        if error_message is not None:
            self.error_message = error_message
        if non_running_tasks is not None:
            self.non_running_tasks = non_running_tasks
        if running_task_count is not None:
            self.running_task_count = running_task_count
        if running_tasks is not None:
            self.running_tasks = running_tasks

    @property
    def error_message(self):
        """Gets the error_message of this MarathonMesosStatus.  # noqa: E501

        Error message when Mesos tasks cannot be queried  # noqa: E501

        :return: The error_message of this MarathonMesosStatus.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this MarathonMesosStatus.

        Error message when Mesos tasks cannot be queried  # noqa: E501

        :param error_message: The error_message of this MarathonMesosStatus.  # noqa: E501
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def non_running_tasks(self):
        """Gets the non_running_tasks of this MarathonMesosStatus.  # noqa: E501

        Non-running tasks associated to this service  # noqa: E501

        :return: The non_running_tasks of this MarathonMesosStatus.  # noqa: E501
        :rtype: list[MarathonMesosNonrunningTask]
        """
        return self._non_running_tasks

    @non_running_tasks.setter
    def non_running_tasks(self, non_running_tasks):
        """Sets the non_running_tasks of this MarathonMesosStatus.

        Non-running tasks associated to this service  # noqa: E501

        :param non_running_tasks: The non_running_tasks of this MarathonMesosStatus.  # noqa: E501
        :type non_running_tasks: list[MarathonMesosNonrunningTask]
        """

        self._non_running_tasks = non_running_tasks

    @property
    def running_task_count(self):
        """Gets the running_task_count of this MarathonMesosStatus.  # noqa: E501

        The number of running Mesos tasks associated to this service  # noqa: E501

        :return: The running_task_count of this MarathonMesosStatus.  # noqa: E501
        :rtype: int
        """
        return self._running_task_count

    @running_task_count.setter
    def running_task_count(self, running_task_count):
        """Sets the running_task_count of this MarathonMesosStatus.

        The number of running Mesos tasks associated to this service  # noqa: E501

        :param running_task_count: The running_task_count of this MarathonMesosStatus.  # noqa: E501
        :type running_task_count: int
        """

        self._running_task_count = running_task_count

    @property
    def running_tasks(self):
        """Gets the running_tasks of this MarathonMesosStatus.  # noqa: E501

        Currently running tasks associated to this service  # noqa: E501

        :return: The running_tasks of this MarathonMesosStatus.  # noqa: E501
        :rtype: list[MarathonMesosRunningTask]
        """
        return self._running_tasks

    @running_tasks.setter
    def running_tasks(self, running_tasks):
        """Sets the running_tasks of this MarathonMesosStatus.

        Currently running tasks associated to this service  # noqa: E501

        :param running_tasks: The running_tasks of this MarathonMesosStatus.  # noqa: E501
        :type running_tasks: list[MarathonMesosRunningTask]
        """

        self._running_tasks = running_tasks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarathonMesosStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MarathonMesosStatus):
            return True

        return self.to_dict() != other.to_dict()
