"""
    Paasta API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""
import pprint
import re  # noqa: F401

import six

from paasta_tools.paastaapi.configuration import Configuration


class MarathonInstanceDrainMethodOneOf:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"drain_method": "str"}

    attribute_map = {"drain_method": "drain_method"}

    def __init__(self, drain_method=None, local_vars_configuration=None):  # noqa: E501
        """MarathonInstanceDrainMethodOneOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._drain_method = None
        self.discriminator = None

        if drain_method is not None:
            self.drain_method = drain_method

    @property
    def drain_method(self):
        """Gets the drain_method of this MarathonInstanceDrainMethodOneOf.  # noqa: E501


        :return: The drain_method of this MarathonInstanceDrainMethodOneOf.  # noqa: E501
        :rtype: str
        """
        return self._drain_method

    @drain_method.setter
    def drain_method(self, drain_method):
        """Sets the drain_method of this MarathonInstanceDrainMethodOneOf.


        :param drain_method: The drain_method of this MarathonInstanceDrainMethodOneOf.  # noqa: E501
        :type: str
        """
        allowed_values = ["noop", "hacheck", "test"]  # noqa: E501
        if (
            self.local_vars_configuration.client_side_validation
            and drain_method not in allowed_values
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `drain_method` ({}), must be one of {}".format(  # noqa: E501
                    drain_method, allowed_values
                )
            )

        self._drain_method = drain_method

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarathonInstanceDrainMethodOneOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MarathonInstanceDrainMethodOneOf):
            return True

        return self.to_dict() != other.to_dict()
