# coding: utf-8

"""
    Paasta API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from paasta_tools.paastaapi.configuration import Configuration


class ResourceValue(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'free': 'float',
        'total': 'float',
        'used': 'float'
    }

    attribute_map = {
        'free': 'free',
        'total': 'total',
        'used': 'used'
    }

    def __init__(self, free=None, total=None, used=None, local_vars_configuration=None):  # noqa: E501
        """ResourceValue - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._free = None
        self._total = None
        self._used = None
        self.discriminator = None

        if free is not None:
            self.free = free
        if total is not None:
            self.total = total
        if used is not None:
            self.used = used

    @property
    def free(self):
        """Gets the free of this ResourceValue.  # noqa: E501


        :return: The free of this ResourceValue.  # noqa: E501
        :rtype: float
        """
        return self._free

    @free.setter
    def free(self, free):
        """Sets the free of this ResourceValue.


        :param free: The free of this ResourceValue.  # noqa: E501
        :type free: float
        """

        self._free = free

    @property
    def total(self):
        """Gets the total of this ResourceValue.  # noqa: E501


        :return: The total of this ResourceValue.  # noqa: E501
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ResourceValue.


        :param total: The total of this ResourceValue.  # noqa: E501
        :type total: float
        """

        self._total = total

    @property
    def used(self):
        """Gets the used of this ResourceValue.  # noqa: E501


        :return: The used of this ResourceValue.  # noqa: E501
        :rtype: float
        """
        return self._used

    @used.setter
    def used(self, used):
        """Sets the used of this ResourceValue.


        :param used: The used of this ResourceValue.  # noqa: E501
        :type used: float
        """

        self._used = used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceValue):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResourceValue):
            return True

        return self.to_dict() != other.to_dict()
