# Stubs for marathon.models.queue (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from .base import MarathonResource as MarathonResource
from .app import MarathonApp as MarathonApp

class MarathonQueueItem(MarathonResource):
    app = ...  # type: Any
    overdue = ...  # type: Any
    count = ...  # type: Any
    delay = ...  # type: Any
    since = ...  # type: Any
    processed_offers_summary = ...  # type: Any
    last_unused_offers = ...  # type: Any
    def __init__(
        self,
        app: Optional[Any] = ...,
        overdue: Optional[Any] = ...,
        count: Optional[Any] = ...,
        delay: Optional[Any] = ...,
        since: Optional[Any] = ...,
        processed_offers_summary: Optional[Any] = ...,
        last_unused_offers: Optional[Any] = ...,
    ) -> None: ...

class MarathonQueueItemDelay(MarathonResource):
    time_left_seconds = ...  # type: Any
    overdue = ...  # type: Any
    def __init__(
        self, time_left_seconds: Optional[Any] = ..., overdue: Optional[Any] = ...
    ) -> None: ...
