-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: check-json
        files: \.(jshintrc|json)$
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: name-tests-test
        files: ^tests/.+\.py$
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
    -   id: requirements-txt-fixer
        language_version: python3.6
    -   id: check-added-large-files
        language_version: python3.6
    -   id: check-byte-order-marker
        language_version: python3.6
    -   id: fix-encoding-pragma
        language_version: python3.6
        args: [--remove]
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
        args: [
            --remove-import, 'from __future__ import absolute_import',
            --remove-import, 'from __future__ import print_function',
            --remove-import, 'from __future__ import unicode_literals',
        ]
