# Stubs for marathon (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .client import MarathonClient as MarathonClient
from .models import (
    MarathonResource as MarathonResource,
    MarathonApp as MarathonApp,
    MarathonTask as MarathonTask,
    MarathonConstraint as MarathonConstraint,
)
from .exceptions import (
    MarathonError as MarathonError,
    MarathonHttpError as MarathonHttpError,
    NotFoundError as NotFoundError,
    InvalidChoiceError as InvalidChoiceError,
)

log = ...  # type: Any
