# Stubs for marathon._compat (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

PY3 = ...  # type: Any
string_types = ...  # type: Any
