# Stubs for marathon.exceptions (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class MarathonError(Exception): ...

class MarathonHttpError(MarathonError):
    error_message = ...  # type: Any
    error_details = ...  # type: Any
    status_code = ...  # type: Any
    def __init__(self, response) -> None: ...

class NotFoundError(MarathonHttpError): ...
class InternalServerError(MarathonHttpError): ...

class InvalidChoiceError(MarathonError):
    def __init__(self, param, value, options) -> None: ...
