# Stubs for marathon.util (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import json
from ._compat import string_types as string_types

def is_stringy(obj): ...

class MarathonJsonEncoder(json.JSONEncoder):
    def default(self, obj): ...

class MarathonMinimalJsonEncoder(json.JSONEncoder):
    def default(self, obj): ...

def to_camel_case(snake_str): ...
def to_snake_case(camel_str): ...
