---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - &worker-entry
    role: worker
    labels:
      yelp.com/pool: default
    extraMounts:
      - hostPath: /nail/etc
        containerPath: /nail/etc
      - hostPath: /nail/srv
        containerPath: /nail/srv
      - hostPath: PAASTA_CHECKOUT_DIR/srv_configs_overlay/acorn
        containerPath: /nail/srv/configs/acorn
      - hostPath: PAASTA_CHECKOUT_DIR/etc_paasta_playground
        containerPath: /etc/paasta
      - hostPath: PAASTA_CHECKOUT_DIR/soa_config_playground
        containerPath: /nail/etc/services
  - *worker-entry
  - *worker-entry
  - *worker-entry
  - *worker-entry
  - *worker-entry
