---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
network: k8s_kindest
nodes:
  - role: control-plane
  - role: worker
    labels:
      yelp.com/pool: default
  - role: worker
    labels:
      yelp.com/pool: default
