---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
network: k8s_kindest
nodes:
  - role: control-plane
  - role: worker
    labels:
      yelp.com/pool: default
    # this mount is needed for services which rely on /nail/etc/{ecosystem,runtime}
    extraMounts:
      - hostPath: /nail/etc
        containerPath: /nail/etc
      - hostPath: /nail/srv
        containerPath: /nail/srv
  - role: worker
    labels:
      yelp.com/pool: default
    # this mount is needed for services which rely on /nail/etc/{ecosystem,runtime}
    extraMounts:
      - hostPath: /nail/etc
        containerPath: /nail/etc
      - hostPath: /nail/srv
        containerPath: /nail/srv
